@startuml ComponentDiagram

package "Chat System" {

  [Client] --> [Room] : Unirse
  [Client] --> [Message] : Enviar/Recibir
  [Room] --> [Message] : Contener mensajes

  [Client] -[hidden]-> [AuthenticationService] : Verificación de sesión
  [Room] -[hidden]-> [RoomService] : Gestión de salas
  [Message] -[hidden]-> [MessageService] : Creación y distribución de mensajes
  
}

@enduml
