@startuml MER

entity "Client" {
  +ID : GUID
  +Alias : string
  +CurrentRoom : Room
}

entity "Room" {
  +ID : GUID
  +Name : string
  +Clients : List<Client>
  +Messages : List<Message>
}

entity "Message" {
  +ID : GUID
  +Sender : Client
  +Content : string
  +Timestamp : DateTime
  +Recipient : Room | Client
}

Client -- Room : has
Room -- Message : contains
Client -- Message : sends

@enduml
